jobs:
- job: Linux_Test
  timeoutInMinutes: 180
  workspace:
    clean: all
  pool: centos7gpu
  steps:
  - checkout: self
    submodules: false
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact - Win x64'
    inputs:
      buildType: specific
      project: '2a773b67-e88b-4c7f-9fc0-87d31fea8ef2'
      definition: 12
      buildVersionToDownload: specific
      pipelineId: 390681
      artifactName: 'drop-linux'
      targetPath: '$(Build.BinariesDirectory)/Release'
      
  - task: CmdLine@2
    inputs:
      script: |
         python3 -m pip uninstall -y onnxruntime -qq
         python3 -m pip install $(Build.BinariesDirectory)/Release/dist/*.whl
         python3 $(Build.SourcesDirectory)/tools/ci_build/build.py \
              --build_dir $(Build.BinariesDirectory) --cmake_generator Ninja \
              --config Release --test \
              --skip_submodule_sync \
              --build_shared_lib \
              --parallel \
              --build_wheel \
              --enable_onnx_tests --use_cuda --cuda_version=11.0 --cuda_home=/usr/local/cuda-11.0 --cudnn_home=/usr/local/cuda-11.0 \
              --enable_pybind --build_java --build_nodejs
              
  - template: templates/component-governance-component-detection-steps.yml
    parameters:
      condition: 'succeeded'